### ISSUE TITLE
V2 written in Rust

### ISSUE THREAD

**Issue by aklinker1** [aklinker1/buildc#11]
Goal here is efficency and speed. Rust greatly improves the binary startup time, which is very important to buildc which spawns itself recursively. Additionally, rust is just faster at reading files and creating hashes. So this should result in a nice performance improvement.

- [x] Implement CLI
- [x] Pre-built binaries for major platforms/architectures
- [x] Postinstall script to replace JS binary with native binary
- [ ] Sign MacOS binaries
- [ ] Test on windows

See the [`rust` branch](https://github.com/aklinker1/buildc/tree/rust) for progress.

![image](https://github.com/user-attachments/assets/a8086887-4656-4b04-aa82-7526f9adcf55)

> Nicer looking CLI too!

### Breaking Changes

1. `buildc --deps-only -- command` &rarr; `buildc deps && command`
2. `cachable` option renamed to `cacheable` to fix typo
3. Bun projects need to allow `buildc`'s `postinstall` script to run: https://bun.sh/docs/cli/install#lifecycle-scripts

### New Features

- `buildc clear` added as an alias for `buildc clean` - I could never remember which one to use, so I added them both!
- Way more efficient logic for composing builds together

### Todo

- Maybe allow parallel builds when possible? Probably not, then I have to deal with console output
